eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
        
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: MICRO
    password: MICRO
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
